name: Publish Package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: 'pub.dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' 
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build package
        run: dart pub publish --dry-run

      - name: Publish to GitHub Packages
        run: dart pub publish