name: Publish Package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'pub.dev'

    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: '3.24.0' 
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Check Publish Warnings
        run: dart pub publish --dry-run

      - name: Publish Package
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
        run: |
          echo $PUB_DEV_TOKEN > ~/Users/senai/Library/Application Support/dart/pub-credentials.json
          dart pub publish -f

        