name: Publish Package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: 'pub.dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Build package
        run: flutter pub publish --dry-run

      - name: Publish to GitHub Packages
        run: flutter pub publish

      - name: Publish to pub.dev
        run: flutter pub publish --server https://pub.dev
